-- Supabase Postgres migration for PrintR Credits Ledger (authoritative)
-- Apply in Supabase SQL editor or via migration tool.
-- Notes:
-- - Uses uuid for ledger ids (generated by backend).
-- - Uses player_ref as the canonical identity (e.g. tg:<telegram_user_id>).

create table if not exists players (
  player_ref text primary key,
  telegram_user_id text,
  wallet_pubkey text,
  display_name text,
  created_at timestamptz not null default now()
);

create table if not exists credits_balances (
  player_ref text primary key references players(player_ref) on delete cascade,
  sessions_balance integer not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists credits_ledger (
  id uuid primary key,
  player_ref text not null references players(player_ref) on delete cascade,
  delta_sessions integer not null,
  reason text not null, -- purchase|consume|refund|adjustment
  source text not null, -- stripe|usdc|system|admin
  external_ref text,    -- stripe session id, session id, etc
  idempotency_key text,
  meta_json jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_credits_ledger_player_ref on credits_ledger(player_ref);
create index if not exists idx_credits_ledger_created_at on credits_ledger(created_at);
create unique index if not exists idx_credits_ledger_idempotency
  on credits_ledger(player_ref, external_ref, idempotency_key)
  where idempotency_key is not null;

create table if not exists webhook_events (
  provider text not null,
  event_id text not null,
  created_at timestamptz not null default now(),
  primary key (provider, event_id)
);

-- Helpful trigger to keep updated_at fresh (optional)
create or replace function set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_balances_updated_at on credits_balances;
create trigger trg_balances_updated_at
before update on credits_balances
for each row execute function set_updated_at();
